In [1]:
%matplotlib inline
from matplotlib import pyplot as plt
import seaborn as sns

In [2]:
import antipackage
from github.ellisonbg.misc import vizarry as va

ImportError: cannot import name 'urlretrieve'

In [3]:
import numpy as np
data = [0,2,4,6]
a=np.array(data)

In [4]:
type(a)

numpy.ndarray

In [5]:
a

array([0, 2, 4, 6])

In [6]:
a.shape

(4,)

In [7]:
a.size

4

In [8]:
a.nbytes

32

In [9]:
a.dtype

dtype('int64')

In [10]:
data = [[0.0,2.0,4.0,6.0],[1.0,3.0,5.0,7.0]]
b=np.array(data)

In [11]:
b

array([[ 0.,  2.,  4.,  6.],
       [ 1.,  3.,  5.,  7.]])

In [12]:
b.shape, b.ndim, b.size, b.nbytes

((2, 4), 2, 8, 64)

In [15]:
c = np.arange(0.0, 10.0, 1.0)
c

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [16]:
e=np.linspace(0.0,5.0,11)
e

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ])

In [18]:
np.empty((4,4))

array([[  6.92831725e-310,   6.92831725e-310,   2.22358789e-317,
          2.47032823e-323],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          4.50620559e-144],
       [  0.00000000e+000,   0.00000000e+000,   2.42290114e-028,
          0.00000000e+000],
       [  0.00000000e+000,   2.35143965e+180,   0.00000000e+000,
          0.00000000e+000]])

In [19]:
np.zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [20]:
np.ones((3,3))


array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [21]:
a=np.array([0,1,2,3])

In [22]:
a, a.dtype

(array([0, 1, 2, 3]), dtype('int64'))

In [26]:
b = np.zeros((2,2), dtype=np.complex64)
b

array([[ 0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j]], dtype=complex64)

In [27]:
c = np.arange(0,10,2, dtype=np.float)
c

array([ 0.,  2.,  4.,  6.,  8.])

In [28]:
d=c.astype(dtype=np.int)

In [29]:
d

array([0, 2, 4, 6, 8])

In [30]:
np.float?


In [31]:
a = np.empty((3,3))
a.fill(0.1)
a

array([[ 0.1,  0.1,  0.1],
       [ 0.1,  0.1,  0.1],
       [ 0.1,  0.1,  0.1]])

In [32]:
b=np.ones((3,3))
b

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [33]:
b/a

array([[ 10.,  10.,  10.],
       [ 10.,  10.,  10.],
       [ 10.,  10.,  10.]])

In [34]:
a**2

array([[ 0.01,  0.01,  0.01],
       [ 0.01,  0.01,  0.01],
       [ 0.01,  0.01,  0.01]])

In [35]:
np.pi*b

array([[ 3.14159265,  3.14159265,  3.14159265],
       [ 3.14159265,  3.14159265,  3.14159265],
       [ 3.14159265,  3.14159265,  3.14159265]])

In [36]:
a=np.random.rand(10,10)

In [37]:
a

array([[ 0.76277943,  0.82250516,  0.85496366,  0.11552364,  0.7758916 ,
         0.40844033,  0.60903385,  0.61041051,  0.26598882,  0.11298096],
       [ 0.58049076,  0.99170965,  0.35016228,  0.25340957,  0.46749081,
         0.57033036,  0.12293623,  0.09043117,  0.69368035,  0.22900142],
       [ 0.11758272,  0.75735492,  0.74762483,  0.07958471,  0.23337248,
         0.16974384,  0.14435034,  0.37196321,  0.24625937,  0.29854967],
       [ 0.20508819,  0.81710077,  0.78585492,  0.27683153,  0.13889566,
         0.48777651,  0.96070566,  0.0220919 ,  0.86369047,  0.88174378],
       [ 0.1189788 ,  0.33025432,  0.9006032 ,  0.71118891,  0.68790649,
         0.77578899,  0.97433579,  0.58485334,  0.93821044,  0.72043986],
       [ 0.69419082,  0.8959113 ,  0.24375404,  0.99493238,  0.302416  ,
         0.35127754,  0.87043536,  0.22199585,  0.21848314,  0.288597  ],
       [ 0.55282496,  0.86823315,  0.3111772 ,  0.43086356,  0.31833669,
         0.51369674,  0.08138796,  0.51582416

In [38]:
a[0,0]

0.76277943093261291

In [40]:
a[-1,-1]==a[9,9]

True

In [41]:
a[:,0]

array([ 0.76277943,  0.58049076,  0.11758272,  0.20508819,  0.1189788 ,
        0.69419082,  0.55282496,  0.20869201,  0.01239632,  0.14093615])

In [42]:
a[-1,:]

array([ 0.14093615,  0.4113426 ,  0.78243267,  0.28027675,  0.63516703,
        0.1675292 ,  0.01379893,  0.3589631 ,  0.08446482,  0.87965592])

In [43]:
a[0:5,0:5]=1.0
a

array([[ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         0.40844033,  0.60903385,  0.61041051,  0.26598882,  0.11298096],
       [ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         0.57033036,  0.12293623,  0.09043117,  0.69368035,  0.22900142],
       [ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         0.16974384,  0.14435034,  0.37196321,  0.24625937,  0.29854967],
       [ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         0.48777651,  0.96070566,  0.0220919 ,  0.86369047,  0.88174378],
       [ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         0.77578899,  0.97433579,  0.58485334,  0.93821044,  0.72043986],
       [ 0.69419082,  0.8959113 ,  0.24375404,  0.99493238,  0.302416  ,
         0.35127754,  0.87043536,  0.22199585,  0.21848314,  0.288597  ],
       [ 0.55282496,  0.86823315,  0.3111772 ,  0.43086356,  0.31833669,
         0.51369674,  0.08138796,  0.51582416